name: GitHub Pages Deploy
on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Setup env 
      run: |
        npm -g install vue
        vue -V
        npm -g i n
        n 14.15.0
    - name: Install and Build 
      run: |
        npm install
        npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_GITHUB_PAGES }}
        BRANCH: deploy
        FOLDER: docs