name: GitHub Pages Deploy
on:
  push:
    branches:
      - deploy
  pull_request:
    branches: 
      - deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_GITHUB_PAGES }}
        BRANCH: deploy
        FOLDER: docs
        BUILD_SCRIPT: npm install && npm run build